getappmap/appmap-java

CHANGELOG.md, build.gradle, src/main/java/com/appland/appmap/output/v1/HttpServerRequest.java, src/main/java/com/appland/appmap/process/hooks/HttpServerRequest.java, src/main/java/com/appland/appmap/process/hooks/Message.java, src/main/java/com/appland/appmap/process/hooks/ToggleRecord.java, src/main/java/com/appland/appmap/record/AppMapSerializer.java, src/main/java/com/appland/appmap/record/Recorder.java, src/test/java/com/appland/appmap/record/RecorderTest.java, test/Dockerfile, test/helper.bash, test/smoke.bats
Adds:
- Name property added to appmap metadata
- HTTP request parameters are captured
- Spring path params are captured
- Spring normalized path info is captured
- Support for JUnit Jupiter
Fixes:
- Feature group metadata is now written to the correct key
There's also an internal change which exposes the last event recorded so that it can be modified by a subsequent hook. See notes in commit fc54213.
=> Testing fixes

README.md
This moves the development testing info into the 'development' section. This makes it clear to end-users who choose the README experience what information pertains only to development.
=> readme revision

CHANGELOG.md, build.gradle, src/main/java/com/appland/appmap/Agent.java, src/main/java/com/appland/appmap/config/AppMapConfig.java, src/main/java/com/appland/appmap/output/v1/CodeObject.java, src/main/java/com/appland/appmap/output/v1/Parameters.java, src/main/java/com/appland/appmap/output/v1/ParametersSerializer.java, src/main/java/com/appland/appmap/process/hooks/HttpServerRequest.java, src/main/java/com/appland/appmap/process/hooks/SqlQuery.java, src/main/java/com/appland/appmap/process/hooks/ToggleRecord.java, src/main/java/com/appland/appmap/record/Recorder.java, src/main/java/com/appland/appmap/record/RecordingSessionFileStream.java, src/main/java/com/appland/appmap/reflect/FilterChain.java, src/main/java/com/appland/appmap/reflect/HttpServletRequest.java, src/main/java/com/appland/appmap/reflect/HttpServletResponse.java, src/main/java/com/appland/appmap/reflect/ReflectiveType.java, src/main/java/com/appland/appmap/transform/ClassFileTransformer.java, src/main/java/com/appland/appmap/transform/annotations/CallbackOnSystem.java, src/main/java/com/appland/appmap/transform/annotations/CtClassUtil.java, src/main/java/com/appland/appmap/transform/annotations/Hook.java, src/main/java/com/appland/appmap/transform/annotations/HookAnnotatedSystem.java, src/main/java/com/appland/appmap/transform/annotations/HookClassSystem.java, src/main/java/com/appland/appmap/transform/annotations/HookConditionSystem.java, src/main/java/com/appland/appmap/util/Logger.java, src/main/java/com/appland/appmap/web/RecordServlet.java
- `javax.servlet` was being bundled by our JAR and potentially loaded by host applications. The dependency was removed and the issue has been resolved.
- Servlet hooks now use reflection as a result.
- Logging is now fully silenced unless `appmap.debug` is present.
- Added support for Jakarta. This means we'll be able to hook more recent versions of Tomcat.
=> Remove leaking dependencies

.gitignore, .travis.yml, CHANGELOG.md, README.md, appmap.yml, build.gradle, src/main/java/com/appland/appmap/Agent.java, src/main/java/com/appland/appmap/config/AppMapConfig.java, src/main/java/com/appland/appmap/config/AppMapPackage.java, src/main/java/com/appland/appmap/config/Properties.java, src/main/java/com/appland/appmap/output/v1/ParametersSerializer.java, src/main/java/com/appland/appmap/output/v1/Value.java, src/main/java/com/appland/appmap/process/hooks/ToggleRecord.java, src/main/java/com/appland/appmap/record/Recorder.java, src/main/java/com/appland/appmap/record/RecordingSessionFileStream.java, src/main/java/com/appland/appmap/record/RecordingSessionGeneric.java, src/main/java/com/appland/appmap/transform/ClassFileTransformer.java, src/main/java/com/appland/appmap/transform/annotations/CallbackOnSystem.java, src/main/java/com/appland/appmap/transform/annotations/CtClassUtil.java, src/main/java/com/appland/appmap/transform/annotations/Hook.java, src/main/java/com/appland/appmap/transform/annotations/HookAnnotatedSystem.java, src/main/java/com/appland/appmap/transform/annotations/HookConditionSystem.java, src/main/java/com/appland/appmap/util/Logger.java, src/test/java/com/appland/appmap/integration/MultithreadedTest.java, src/test/java/com/appland/appmap/integration/RecorderTest.java, src/test/java/com/appland/appmap/test/util/LockedResource.java, src/test/java/com/appland/appmap/test/util/MyClass.java
This PR includes various fixes and changes I've made as a result of a bunch of testing with Jenkins. This is also a follow up to some issues observed during user testing, namely the deadlock fix.
- **Removed a potential deadlock** that could occur if the user's code required a lock in `toString`.
- `appmap.event.valueSize` can be used to specify the length of a value string before truncation occurs.
- `Recorder.record` will record and output the execution of a `Runnable`. Examples can be found [here](https://github.com/applandinc/appmap-java/blob/60a83b18ba1164ce6f10bdfb3c4e6fba4d048b97/src/test/java/com/appland/appmap/integration/RecorderTest.java#L41-L45) and [here](https://github.com/applandinc/appmap-java/blob/60a83b18ba1164ce6f10bdfb3c4e6fba4d048b97/src/test/java/com/appland/appmap/in …
=> Jenkins testing enhancements

CHANGELOG.md, appmap.yml, build.gradle, buildSrc/src/main/groovy/com/appland/tasks/ShadowRelocation.groovy, src/main/java/com/appland/appmap/Agent.java, src/main/java/com/appland/appmap/config/AppMapConfig.java, src/main/java/com/appland/appmap/process/ThreadLock.java, src/test/java/com/appland/appmap/integration/ThreadTest.java, src/test/java/com/appland/appmap/test/util/MyThread.java, src/test/java/com/appland/appmap/test/util/UnhandledExceptionCollection.java
`0.3.1` Fixes issues spotted in the wild:
- Dependencies of `appmap-java` which use `slf4j` will now use a nop implementation in order to stop them from logging if the client application provides it's own implementation. If left up to the client application, `appmap-java` can interfere with test frameworks by corrupting stdout.
- `appmap-java` will no longer call `Thread` methods that may be extended by the client application resulting in a stack overflow.
- `appmap-java` no longer assumes that `Thread` identifiers are unique. Previously, this could result in concurrent modificiations to resources not meant to be shared across threads.
=> Testing behavior is the same with/without the agent attached

CHANGELOG.md, build.gradle, src/main/java/com/appland/appmap/process/hooks/ToggleRecord.java
Tests annotated with `org.testng.annotations.Test` are now recorded.
=> Add support for TestNG

.travis.yml, CHANGELOG.md, build.gradle, src/main/java/com/appland/appmap/config/Properties.java, src/main/java/com/appland/appmap/output/v1/CodeObject.java, src/main/java/com/appland/appmap/output/v1/NoSourceAvailableException.java, src/main/java/com/appland/appmap/output/v1/Parameters.java, src/main/java/com/appland/appmap/record/CodeObjectTree.java, src/main/java/com/appland/appmap/transform/ClassFileTransformer.java, src/main/java/com/appland/appmap/transform/annotations/Hook.java, src/main/java/com/appland/appmap/util/Logger.java, test/entrypoint
These changes improve the agent so it uses less memory while recording. 
For example, when recording the `jetty-server` tests in https://github.com/land-of-apps/jetty.project, memory usage for v0.4.0 of the agent looks like this:
With these changes, it looks like this:
There's still more room for improvement, though. With the agent, memory usage looks like this:
These changes also add support for hooking methods that have been compiled with `-g:vars`. It's currently turned off, though, because enabling it broke the end-to-end tests with petclinic.
Finally, I tried to make logging a bit more useful, and to make it easier to diagnose test failures.
=> Use less memory when recording

CHANGELOG.md, src/main/java/com/appland/appmap/config/Properties.java, src/main/java/com/appland/appmap/output/v1/CodeObject.java, src/main/java/com/appland/appmap/record/CodeObjectTree.java, src/main/java/com/appland/appmap/record/IRecordingSession.java, src/main/java/com/appland/appmap/record/Recorder.java, src/main/java/com/appland/appmap/record/RecordingSessionFileStream.java, src/main/java/com/appland/appmap/record/RecordingSessionGeneric.java, src/main/java/com/appland/appmap/record/RecordingSessionMemory.java, src/main/java/com/appland/appmap/transform/ClassFileTransformer.java, src/main/java/com/appland/appmap/util/Logger.java, src/test/java/com/appland/appmap/record/RecorderTest.java, test/entrypoint, test/helper.bash, test/smoke.bats
See additional comments on the individual commits for more details of these changes. Might be easiest to review them one by one.
Memory usage in 0.4.0 for the jetty-server submodule in land-of-apps/jetty.project:
Memory usage now:
=> Fix classmap generation

CHANGELOG.md, build.gradle, gradle/wrapper/gradle-wrapper.properties, src/main/java/com/appland/appmap/config/Properties.java, src/main/java/com/appland/appmap/process/hooks/ToggleRecord.java, src/main/java/com/appland/appmap/reflect/FilterChain.java, src/main/java/com/appland/appmap/reflect/HttpServletRequest.java, src/main/java/com/appland/appmap/reflect/HttpServletResponse.java, src/main/java/com/appland/appmap/reflect/ReflectiveType.java, src/main/java/com/appland/appmap/web/RecordServlet.java
Added the new system property `appmap.debug.http` to show some debugging when handling requests for `/_appmap/record`.
Cleaned up reflection in `HttpServletRequest`, `HttpServletResponse`, and `FilterChain`.
=> Add some logging, clean up some uses of reflection

CHANGELOG.md, build.gradle, src/main/java/com/appland/appmap/reflect/ReflectiveType.java
ReflectiveType.invoke needs to make the method accessible before trying
to invoke it.
=> Make method accessible before invoking

README.md
added `appmap.yml` setup instructions to README (modified instructions from appmap-ruby README)
=> Add appmap.yml instructions to README

.travis.yml, CI-README.md, bin/multiline_input_to_travis_env.py, bin/test, build.gradle
* Support publication to OSSRH repo (both manual and Travis-managed) for the Agent, 
* Meet Maven Central requirements to Agent artifacts, 
* Fix Travis docker pull issue (anonymous pulls fail regularly due to exceeding Dockerhub's rate limits)
Changes squashed into cumulative commit
More details and release management guide in [CI-README.md](https://github.com/hleb-rubanau/appmap-java/blob/agent-publication-travis-maven/CI-README.md)
=> Support publication of AppMapAgent to OSSRH repo 

src/main/java/com/appland/appmap/process/hooks/HttpClientRequest.java, test/smoke.bats
Until the bootclass path hack can be removed, this must be disabled.
=> fix: disable http client requests

src/main/java/com/appland/appmap/output/v1/CodeObject.java, src/test/java/com/appland/appmap/output/v1/CodeObjectTest.java, src/test/java/com/appland/appmap/output/v1/testclasses/Anonymous.java, src/test/java/com/appland/appmap/output/v1/testclasses/ExampleInnerClass.java
Original PR: #57 
This removes hard coded path prefixes from the source file path heuristics and fixes a potential null access when reading a class package.
=> fix: improve path and package resolution

src/main/java/com/appland/appmap/output/v1/ParametersSerializer.java, src/main/java/com/appland/appmap/record/EventTemplateRegistry.java, src/main/java/com/appland/appmap/transform/ClassFileTransformer.java, src/main/java/com/appland/appmap/transform/annotations/CallbackOnSystem.java, src/main/java/com/appland/appmap/transform/annotations/CtClassUtil.java, src/main/java/com/appland/appmap/transform/annotations/Hook.java, src/main/java/com/appland/appmap/transform/annotations/HookConditionSystem.java, src/main/java/com/appland/appmap/util/Logger.java, src/test/java/com/appland/appmap/record/EventTemplateRegistryTest.java
This change:
- Prevents unexpected exceptions from being raised within the host application
- Logs full stack traces on exception and moves some debug logging behind the "hooks" flag
- Potentially (untested) speeds up method hooks
=> Fix: Dont panic on unknown event ordinal

src/main/java/com/appland/appmap/transform/ClassFileTransformer.java
See:
https://www.javassist.org/html/javassist/ClassPool.html#%3Cinit%3E(boolean)
In rare cases, appending the System path here caused ClassDefNotFound
exceptions to be raised from within user code.
=> fix: Don't append System path to class pools

README.md, src/main/java/com/appland/appmap/Agent.java, src/main/java/com/appland/appmap/config/Properties.java, src/main/java/com/appland/appmap/process/hooks/ToggleRecord.java, src/main/java/com/appland/appmap/record/Recorder.java, src/main/java/com/appland/appmap/record/RecordingSessionFileStream.java
Specifying `-Dappmap.recording.auto=true` prompts the agent to automatically begin recording upon boot. An AppMap will be emitted upon exit.
=> Feature: Add a System property to automatically start recording

src/main/java/com/appland/appmap/Agent.java, src/main/java/com/appland/appmap/config/AppMapConfig.java, src/main/java/com/appland/appmap/config/AppMapPackage.java, src/main/java/com/appland/appmap/config/Properties.java, src/main/java/com/appland/appmap/output/v1/Event.java, src/main/java/com/appland/appmap/process/hooks/ToggleRecord.java, src/main/java/com/appland/appmap/record/Recorder.java, src/main/java/com/appland/appmap/record/RecordingSession.java, src/main/java/com/appland/appmap/transform/ClassFileTransformer.java, src/main/java/com/appland/appmap/transform/annotations/CallbackOnSystem.java, test/agent-cli/.gitignore
* feat: Implement `shallow` mode …
Packages can be marked `shallow`.
In shallow recording mode, subsequent calls to the same package are ignored, until the call stack leaves the package.
This helps to make the trace diagram more compact.
* feat: Ignore common methods …
Ignore getters, setters, and certain common methods on `java.lang.Object`.
* fix: Respect the output directory
=> feat: Package recording options

src/main/java/com/appland/appmap/Agent.java, src/main/java/com/appland/appmap/config/AppMapConfig.java, src/test/java/com/appland/appmap/config/AppMapConfigTest.java
If appmap.yml doesn't exist in the current directory, scan the parent directories for it.
Also, we now abort if we can't find a config file. Continuing with an empty config is likely to produce empty AppMaps and cause confusion.
=> Look for config in parent directories

src/main/java/com/appland/appmap/record/Recorder.java
If Recorder.threadState() is called concurrently with Recorder.flush(),
a ConcurrentModificationException may be raised. This happens because
threadState() updates the threadState HashMap while flush() is iterating
over its elements.
This change switches threadState to a ConcurrentHashMap, which allows
concurrent operations.
=> fix: Avoid ConcurrentModificationException

build.gradle, src/main/java/com/appland/appmap/record/Recorder.java, src/test/java/com/appland/appmap/record/RecorderTest.java
Multiple threads can access Recorder.threadState. For example, one
thread may be adding a new event while another is calling checkpoint().
A previous commit allowed such concurrent access. This commit adds a
test for that change.
=> test: Test access to Recorder.threadState

src/main/resources/config-schema.yml
The path attribute of a package, as well as the items in an exclude
array, can have '$' in them. Fix the regexp in the config schema to
reflect this.
No tests here, it's `@appland/appmap` that actually uses the config schema.
=> fix: Fix path and exclude item regexp

bin/test_run, src/main/java/com/appland/appmap/config/Properties.java, src/main/java/com/appland/appmap/process/conditions/ConfigCondition.java, src/main/java/com/appland/appmap/process/conditions/RecordCondition.java, src/main/java/com/appland/appmap/transform/ClassFileTransformer.java, src/main/java/com/appland/appmap/util/AppMapBehavior.java, src/test/java/com/appland/appmap/test/util/MyClass.java, test/access/.gitignore, test/access/RecordPackage.java, test/access/access.bats, test/access/test
By default, we'll now record methods with protected and package access.
Additionally, if the property appmap.record.private is true, we'll
capture private methods, too.
=> feat: Record non-public methods

src/main/java/com/appland/appmap/output/v1/Event.java, src/main/java/com/appland/appmap/process/hooks/HttpServerRequest.java, src/main/java/com/appland/appmap/process/hooks/remoterecording/HttpCoreAsyncHooks.java, src/main/java/com/appland/appmap/process/hooks/remoterecording/HttpCoreHooks.java, src/main/java/com/appland/appmap/transform/ClassFileTransformer.java, src/main/java/com/appland/appmap/transform/annotations/AnnotationUtil.java, src/main/java/com/appland/appmap/transform/annotations/BaseSystem.java, src/main/java/com/appland/appmap/transform/annotations/Hook.java, src/main/java/com/appland/appmap/transform/annotations/HookClass.java, src/main/java/com/appland/appmap/transform/annotations/HookClassSystem.java, src/main/java/com/appland/appmap/transform/annotations/ISystem.java, test/httpcore/appmap.yml, test/httpcore/build.gradle, test/httpcore/httpcore.bats, test/httpcore/src/test/java/org/apache/http/examples/nio/HelloWorldServer.java, test/httpcore/test
These changes add support for capturing `http_server_request` and `http_server_response` events made to an Http Core server.
Http Core doesn't have a mechanism analogous to servlet filters. We're hooking the `handle` method in any class that implements `HttpRequestHandler` (e.g. https://github.com/applandinc/appmap-java/compare/core-server-request_20220217?expand=1#diff-52444c960044bb2cfe82e757cfa55ea0f9a414a6cede6d255ec32275ecc0f3e0R23) to generate `http_request_*` events. It's likely that this method will also be hooked to generate method `call` and `return` events. To ensure that all these events get added correctly, I needed to add a mechanism to control the order of hook application (see d111e0a).
=> Add support for recording HTTP server requests to an Http Core server

src/main/java/com/appland/appmap/Agent.java, src/main/java/com/appland/appmap/annotation/Labels.java, src/main/java/com/appland/appmap/output/v1/CodeObject.java, test/httpcore/httpcore.bats, test/httpcore/src/test/java/org/apache/http/examples/nio/HelloWorldServer.java, test/httpcore/test
These changes add support for labeling functions. The also get rid of a stray `whereAmI` that was appearing at agent startup.
The doc still needs to be updated, but you can see a sample usage here: https://github.com/applandinc/appmap-java/compare/labels_20220201?expand=1#diff-52444c960044bb2cfe82e757cfa55ea0f9a414a6cede6d255ec32275ecc0f3e0
=> Add @Labels annotation

agent/src/main/java/com/appland/appmap/process/hooks/SqlQuery.java, agent/src/test/java/com/appland/appmap/integration/MockerTest.java
When recording a SQL query, make sure we don't call methods of objects
that have been mocked. Doing so is likely to break the user's tests.
Fixes #129.
This currently only checks for Mockito. In follow-on work, I'm planning to make the choice of mocking frameworks configurable in `appmap.yml`.
=> fix: Don't call mocked java.sql methods

agent/build.gradle, agent/src/main/java/com/appland/appmap/util/FullyQualifiedName.java, agent/src/test/java/com/appland/appmap/config/AppMapPackageTest.java, agent/src/test/java/com/appland/appmap/util/FullyQualifiedNameTest.java
A `CtBehavior` for a class in the unnamed package returns `null` for it's package name. This change handles that case in `FullyQualifiedName` by returning `""` instead.
Also, these changes switch to using JUnit 5 for new tests. Existing tests still use JUnit conventions (enabled by including `junit-vintage-engine`).
=> Fix NPE that happens when examining a class in the unnamed package

agent/src/main/java/com/appland/appmap/process/hooks/HttpServerRequest.java, agent/test/petclinic/petclinic.bats
Only set `normalized_path_info` for parameterized requests. Update the syntax so it matches v1.5.1 of the [AppMap spec](https://github.com/getappmap/appmap#http-server-request-call-attributes).
Fixes #151. Fixes #152.
=> Handle Spring parameterized requests correctly

agent/bin/test_run, agent/src/main/java/com/appland/appmap/Agent.java, agent/src/main/java/com/appland/appmap/config/AppMapPackage.java, agent/src/main/java/com/appland/appmap/process/hooks/remoterecording/RemoteRecordingManager.java, agent/src/main/java/com/appland/appmap/process/hooks/remoterecording/ServletHooks.java, agent/src/main/java/com/appland/appmap/record/AppMapSerializer.java, agent/src/main/java/com/appland/appmap/record/Recorder.java, agent/src/main/java/com/appland/appmap/record/Recording.java, agent/src/main/java/com/appland/appmap/record/RecordingSession.java, agent/src/main/java/com/appland/appmap/reflect/HttpHeaders.java, agent/src/main/java/com/appland/appmap/transform/annotations/Hook.java, agent/src/test/java/com/appland/appmap/output/v1/testclasses/ExampleInnerClass.java, agent/src/test/java/com/appland/appmap/record/EventTemplateRegistryTest.java, agent/src/test/java/com/appland/appmap/record/RecorderTest.java, agent/test/agent_cli/test, agent/test/http_client/test, agent/test/httpcore/build.gradle, agent/test/httpcore/test, agent/test/jdbc/jdbc.bats, agent/test/jdbc/test, agent/test/junit/test, agent/test/petclinic/petclinic-tests.bats, agent/test/petclinic/petclinic.bats, eclipse-java-google-style.xml
Set the name of the output directory to match the name of the recorder. Also, make sure recorder.name and recorder.type are set in an AppMap's metadata.
Fixes #154. Fixes #150.
=> fix: improve naming of output directory

agent/src/main/java/com/appland/appmap/process/hooks/SqlQuery.java
When SQLQuery tries to determine whether an object is a mock, it should not assume that the object has package info available.
We've seen this happen in the wild. I'm not sure why, though, so I don't know how to write a test for it.
Fixes #160 .
=> fix: eliminate possibility of NPE

agent/src/main/java/com/appland/appmap/record/Recording.java, agent/src/test/java/com/appland/appmap/record/RecorderTest.java
Before this change, when `moveTo` copied a file across filesystems it triggered and caught an `AtomicMoveNotSupportedException` exception, printed it out, and then tried to copy the file in other ways which eventually succeeded.  This had the side  effect of printing the exception even though `moveTo` succeeded.
After this change, `moveTo` doesn't print any exceptions if it succeeds.
- Added two tests that verify the exceptions were and still are caught correctly.  They are the tests `testWriteFileAcrossFilesystems` and  `testCantOverwriteTargetFile`.  Didn't add a third test for the [third FileMover](https://github.com/getappmap/appmap-java/blob/master/agent/src/main/java/com/appland/appmap/record/Recording.java#L55) for Files.copy because it seems to be covered by …
=> fix: Don't print exception when copying across filesystems fails

.travis.yml
Deploying [breaks](https://app.travis-ci.com/github/getappmap/appmap-java/builds/260432108) because semantic-release [needs](https://app.travis-ci.com/github/getappmap/appmap-java/jobs/595398075#L503) node >= 18.
```
[semantic-release]: node version >=18 is required. Found v16.19.0.
```
To confirm this fix works, I tested this change in a [`before_install`](https://github.com/getappmap/appmap-java/commit/ad3790d675d52ab4b87e2cd6800ef160ee3063ae) section on branch `sw/fix_deploy__debug_ci`.  It worked on [CI](https://app.travis-ci.com/github/getappmap/appmap-java/jobs/595586760#L214).
=> ci: Fix deploying

.travis.yml
Node 18 (used by semantic release) needs >= GLIBC_2.28.
Focal provides GLIBC_2.28 but openjdk8 seems broken on it.
Jammy provides GLIBC_2.28 and openjdk8 works on it.  Use Jammy.
=> ci: Use Jammy

agent/src/main/java/com/appland/appmap/cli/Init.java, agent/test/agent_cli/sampleproj/src/main/java/unnamed.java
When searching for packages to add to the default config, don't crash if a file is encountered in the unnamed package (i.e. a .java file in src/main/java).
Fixes #158
=> fix: don't crash on unnamed package

agent/src/main/java/com/appland/appmap/Agent.java, agent/src/main/java/com/appland/appmap/cli/Init.java, agent/src/main/java/com/appland/appmap/config/AppMapConfig.java, agent/src/main/java/com/appland/appmap/config/Properties.java, agent/src/main/java/com/appland/appmap/util/Logger.java, agent/src/test/java/com/appland/appmap/config/AppMapConfigTest.java
If there's no appmap.yml in the current project, and the user hasn't explicitly specified one (by setting appmap.config.file), create one.
Fixes #169 .
=> feat: generate a default config

agent/build.gradle, agent/src/main/java/com/appland/appmap/config/AppMapConfig.java, agent/src/main/java/com/appland/appmap/process/hooks/HttpClientRequest.java, agent/src/main/java/com/appland/appmap/reflect/HttpServletRequest.java, agent/src/main/java/com/appland/appmap/reflect/apache/HttpEntity.java, agent/src/main/java/com/appland/appmap/reflect/apache/HttpResponse.java, agent/test/helper.bash, agent/test/http_client/NoContentController.java, agent/test/http_client/http_client.bats, agent/test/http_client/src/main/java/http_client/HttpClientTest.java, agent/test/petclinic/petclinic.bats
Make sure message and parameters are set correctly for an http_client_request. Also, make sure a response without Content-Type header or body is handled correctly.
Also, now that the VSCode does a good job of handling large AppMaps, don't set `shallow: true` when generating the default config.
Fixes #175 .
=> fix: set attributes of http_client_request

agent/build.gradle, agent/src/main/java/com/appland/appmap/process/hooks/HttpClientRequest.java, agent/src/main/java/com/appland/appmap/process/hooks/HttpServerRequest.java, agent/src/main/java/com/appland/appmap/reflect/apache/HttpHost.java, agent/src/main/java/com/appland/appmap/reflect/apache/HttpRequest.java, agent/src/main/java/com/appland/appmap/reflect/apache/RequestLine.java, agent/src/main/java/com/appland/appmap/transform/annotations/CtClassUtil.java, agent/src/main/java/com/appland/appmap/transform/annotations/HookClassSystem.java, agent/src/main/java/com/appland/appmap/transform/annotations/Signature.java, agent/src/main/java/com/appland/appmap/transform/annotations/Signatures.java, agent/src/test/java/com/appland/appmap/transform/annotations/ArgumentArraySystemTest.java, agent/src/test/java/com/appland/appmap/transform/annotations/HookClassSystemTest.java, agent/test/helper.bash, agent/test/http_client/build.gradle, agent/test/http_client/http_client.bats, agent/test/http_client/src/main/java/http_client/HttpHostTest.java, agent/test/httpcore/build.gradle, agent/test/jdbc/build.gradle
Hook a couple more overloads of the `execute` method in `org.apache.http.client.HttpClient`. These changes also include a mechanism to make it easier to hook overloaded methods. They also switch from using `okhttp` to using `spring-web` for URL parsing.
Fixes #177 .
=> Hook HttpClient.execute methods that take an HttpHost

agent/bin/test_install, agent/bin/test_run, agent/build.gradle, agent/src/main/java/com/appland/appmap/transform/ClassFileTransformer.java, agent/src/main/java/com/appland/appmap/transform/annotations/HookClassSystem.java, agent/test/helper.bash, agent/test/petclinic-fw/appmap.yml, agent/test/petclinic-fw/petclinic-fw.bats, agent/test/petclinic-fw/test
Remove the dependency on org.springframework:spring-web, it should have been removed as part of the changes to implement request recording.
Its inclusion prevents hooking of
SpringServletContainerInitializer.onStartup, which keeps request recording doesn't work for a Spring app deployed as a WAR. So, these changes also add a test for such an app.
=> fix: don't depend on spring-web

agent/build.gradle, agent/src/main/java/com/appland/appmap/process/hooks/RequestRecording.java, agent/src/main/java/com/appland/appmap/process/hooks/http/HttpServerRequest.java, agent/src/main/java/com/appland/appmap/process/hooks/http/ServletListener.java, agent/src/main/java/com/appland/appmap/reflect/HttpServletRequest.java, agent/test/helper.bash, agent/test/httpcore/httpcore.bats, agent/test/petclinic-fw/petclinic-fw.bats, agent/test/petclinic-shared/static-resources.bash, agent/test/petclinic/petclinic-no-requests.bats, agent/test/petclinic/petclinic.bats, agent/test/spark/spark.bats
When running a Spring app, don't generate request recordings for static
resources.
Fixes #203 .
=> Don't generate AppMaps for static resources

.travis.yml, agent/bin/test_install, agent/src/main/java/com/appland/appmap/process/hooks/SpringBoot.java, agent/src/main/java/com/appland/appmap/process/hooks/http/HttpServerRequest.java, agent/src/test/fixture/petclinic/ShowAvailable.java, agent/test/helper.bash, agent/test/http_client/http_client.bats, agent/test/httpcore/test, agent/test/petclinic-fw/petclinic-fw.bats, agent/test/petclinic-shared/message-params.bash, agent/test/petclinic-shared/static-resources.bash, agent/test/petclinic/petclinic-tests.bats, agent/test/petclinic/petclinic.bats
The agent should not cause the body of a request to be read, e.g. by
getting the parameter map before HttpServlet.service is invoked.  These
changes avoid this by calling getParameterMap after HttpServlet.service
returns.
Also fixes a couple of other bugs I noticed while working on this one.
Fixes #199 .
=> Don't read the servlet's InputStream

agent/src/main/java/com/appland/appmap/config/AppMapConfig.java, agent/src/main/java/com/appland/appmap/config/Properties.java, agent/src/test/java/com/appland/appmap/config/OutputDirectoryTest.java, agent/test/spark/app/appmap.yml
Make sure Properties.OutputDirectory is set correctly when the config contains appmap_dir and system property appmap.output.directory is unset. Prior to these changes, OutputDirectory was getting set to a default value, rather than what the config contained.
Fixes #204 .
=> fix: handle unset appmap.output.directory

agent/src/main/java/com/appland/appmap/config/AppMapConfig.java, agent/src/test/java/com/appland/appmap/config/OutputDirectoryTest.java, agent/test/jdbc/jdbc.bats, agent/test/petclinic-fw/petclinic-fw.bats, agent/test/petclinic-shared/static-resources.bash, agent/test/petclinic/petclinic-tests.bats, agent/test/petclinic/petclinic.bats, agent/test/spark/app/appmap.yml, agent/test/spark/spark.bats
Undo the recent change that made the default output directory depend on the project's build tool. It's always tmp/appmap now.
Fixes #210.
=> feat: make tmp/appmap the default output directory

agent/src/main/java/com/appland/appmap/process/hooks/RequestRecording.java, agent/test/petclinic-shared/static-resources.bash, agent/test/petclinic/petclinic-tests.bats
The type of a request recording should be `requests`, not `request`.
Fixes #223.
=> fix: set request recording type correctly

agent/src/main/java/com/appland/appmap/output/v1/Parameters.java, agent/src/main/java/com/appland/appmap/transform/annotations/Hook.java, agent/src/main/java/com/appland/appmap/transform/annotations/SourceMethodSystem.java
There are times when classes can be expected to be missing. See the comment in Parameters.java for further details.
Fixes #241 .
=> fix: decrease logging about missing classes

agent/src/main/java/com/appland/appmap/process/hooks/test/TestSupport.java, agent/src/main/java/com/appland/appmap/util/ClassUtil.java, agent/src/test/fixture/petclinic/src/test/java/org/springframework/samples/petclinic/JUnit5Tests.java, agent/test/petclinic/petclinic-tests.bats
Test methods in JUnit 5 can take parameters (to make use of [extensions](https://junit.org/junit5/docs/current/user-guide/#extensions)). These changes take that into account.
Fixes #240 .
=> support JUnit 5 test methods with parameters

agent/src/main/java/com/appland/appmap/Agent.java, agent/src/main/java/com/appland/appmap/process/hooks/ProxyHooks.java, agent/test/classloading/app/src/main/java/com/appland/appmap/test/fixture/TestProxy.java, agent/test/classloading/lib/src/main/java/com/appland/appmap/test/fixture/helloworld/HelloWorld.java, agent/test/intellij/intellij.bats
Instead of using ProtectionDomain.getCodeSource to find the agent jar,
use the ClassLoader that loaded Agent.class. The CodeSource might be
null (e.g. when testing the IntelliJ plugin), but the class loader will
always be able to say where Agent.class was loaded from.
Also, avoid an NPE when a Proxy method returns void.
Fixes #257 .
Fixes #258 .
=> Don't locate Agent jar using ProtectionDomain.getCodeSource

agent/src/main/java/com/appland/appmap/process/hooks/Spark.java, agent/test/helper.bash, agent/test/petclinic/jetty.bats, agent/test/petclinic/petclinic-tests.bats, pomupdater/src/main/java/com/appland/appmap/util/PomUpdater.java
When instrumenting a Jetty server, only add a Spark handler if the app is really a Spark app. A mistake in the code meant that it added the handler whenever running in a Jetty server. This would cause request recording to fail (and maybe cause other problems, as well).
Fixes #265 .
=> fix: correct detection of Spark server

agent/src/main/java/com/appland/appmap/config/Properties.java
Don't create a log file by default until it's better managed.
=> fix: don't create a log file by default

agent/src/main/java/com/appland/appmap/config/AppMapConfig.java, agent/src/main/java/com/appland/appmap/config/Properties.java, agent/src/test/java/com/appland/appmap/config/AppMapConfigTest.java, agent/src/test/java/com/appland/appmap/config/OutputDirectoryTest.java, agent/test/access/access.bats, agent/test/helper.bash, agent/test/httpcore/httpcore.bats, agent/test/petclinic/petclinic-tests.bats, agent/test/scala/scala.bats
The `appmap_dir` specified in a config file should be resolved relative to the location of the config file.
For example, if appmap.yml is in the root of project, contains `appmap_dir: tmp/appmap`, and is discovered for tests in a submodule run by maven, the AppMaps will be in `$project_root/tmp/appmap`. Prior to these changes, the recordings were placed in `$project_root/$submodule_dir/tmp/appmap`.
Fixes #271 .
=> fix: resolve output directory relative to config

agent/src/main/java/com/appland/appmap/process/hooks/RecordingSupport.java, agent/src/main/java/com/appland/appmap/process/hooks/RequestRecording.java, agent/src/main/java/com/appland/appmap/record/Recorder.java, agent/src/test/java/com/appland/appmap/record/RecorderTest.java
This patch should similarly fix #75 as in https://github.com/getappmap/appmap-python/issues/91
=> fix: filename too long in some cases

.github/workflows/build.yml, agent/src/main/java/com/appland/appmap/config/AppMapConfig.java, agent/test/agent_cli/agent_cli.bats
If there is no `appmap.yml` anywhere in the current directory tree, the `init` subcommand will fail with a NullPointerException. These changes make sure that doesn't happen.
Fixes #280 .
=> fix: fix NPE running init when no appmap.yml found

agent/src/main/java/com/appland/appmap/config/AppMapConfig.java, agent/src/test/java/com/appland/appmap/config/AppMapConfigTest.java, agent/test/intellij/intellij.bats
Fixes #285.
This PR addresses an issue where the AppMap agent crashes due to a malformed configuration file, specifically when the `packages` key value is missing. The changes ensure that such scenarios are handled gracefully, avoiding null pointer exceptions.
- Treat empty 'packages:' entry as empty array to prevent NPE. Ensures consistent behavior with when no 'packages:' entry or 'packages: []' is specified.
- Log and return null instead of System.exit(1) on 'load', since System.exit(1) is already done in 'initialize.'
Added tests to verify:
- Loading config with 'packages' key having no value.
- Error message for scalar 'packages' value.
```java
ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
try {
singleton = mapper.readValue(inputStream, AppMapConfig.class);
// If an …
```
=> fix: crash due to config packages key with missing value

agent/src/main/java/com/appland/appmap/config/AppMapConfig.java, agent/src/test/java/com/appland/appmap/config/AppMapConfigTest.java, agent/test/agent_cli/agent_cli.bats, agent/test/agent_cli/sampleproj/subproj/p1/src/main/java/com/example/subprojpkg1/Class1.java, agent/test/agent_cli/sampleproj/subproj/p2/src/main/java/com/example/subprojpkg2/Class2.java, agent/test/intellij/.gitignore
Fixes #283.
This PR addresses the issue of failure to autodetect package names in some multi-project repositories. Specifically, the Java AppMap agent was unable to auto-detect packages in the multi-project structure of the [Retrofit](https://github.com/square/retrofit) repository. The agent only looked for `src/main/java` directories, which led to an `appmap.yml` configuration file with no detected packages, as shown below:
```yaml
name: retrofit
packages: []
```
The repository is structured with multiple subprojects, each containing their own `src/main/java` directories:
1. **AppMapConfig.java**: Updated `AppMapConfig.java` to traverse the root directory and collect packages from all relevant `src/main/java` directories across subprojects.
- Introduced a method `collectPackages` to …
=> fix: detect packages in multi-project repositories

agent/src/main/java/com/appland/appmap/output/v1/Parameters.java
This pull request includes an important refactor in the `Parameters` class to improve the handling of local variables and parameter names in hopes of fixing #293. The changes focus on iterating through local variables to accurately match slots and handle potential issues with corrupted debug information.
Improvements to local variable handling:
* [`agent/src/main/java/com/appland/appmap/output/v1/Parameters.java`](diffhunk://#diff-f31f8cbd0429051e6b32b0948775d97ea92fe7e47e521f00ed38b65c7528fef5R96-R126): Refactored the logic to iterate through local variables to find matching slots for parameters, including handling cases where the debug information might be corrupted. The new approach ensures that parameters are correctly identified even if the local variable table is out of order.
=> fix: More robust handling of LVT when resolving parameters
